#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNS")]
	public partial class QLNSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblTrinhdo(tblTrinhdo instance);
    partial void UpdatetblTrinhdo(tblTrinhdo instance);
    partial void DeletetblTrinhdo(tblTrinhdo instance);
    partial void InserttblChucvu(tblChucvu instance);
    partial void UpdatetblChucvu(tblChucvu instance);
    partial void DeletetblChucvu(tblChucvu instance);
    partial void InserttblHopdong(tblHopdong instance);
    partial void UpdatetblHopdong(tblHopdong instance);
    partial void DeletetblHopdong(tblHopdong instance);
    partial void InserttblHoso(tblHoso instance);
    partial void UpdatetblHoso(tblHoso instance);
    partial void DeletetblHoso(tblHoso instance);
    partial void InserttblLoaitaikhoan(tblLoaitaikhoan instance);
    partial void UpdatetblLoaitaikhoan(tblLoaitaikhoan instance);
    partial void DeletetblLoaitaikhoan(tblLoaitaikhoan instance);
    partial void InserttblLuong(tblLuong instance);
    partial void UpdatetblLuong(tblLuong instance);
    partial void DeletetblLuong(tblLuong instance);
    partial void InserttblPhong(tblPhong instance);
    partial void UpdatetblPhong(tblPhong instance);
    partial void DeletetblPhong(tblPhong instance);
    partial void InserttblTaikhoan(tblTaikhoan instance);
    partial void UpdatetblTaikhoan(tblTaikhoan instance);
    partial void DeletetblTaikhoan(tblTaikhoan instance);
    #endregion
		
		public QLNSDataContext() : 
				base(global::QuanLyNhanSu.Properties.Settings.Default.QLNSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblTrinhdo> tblTrinhdos
		{
			get
			{
				return this.GetTable<tblTrinhdo>();
			}
		}
		
		public System.Data.Linq.Table<tblChucvu> tblChucvus
		{
			get
			{
				return this.GetTable<tblChucvu>();
			}
		}
		
		public System.Data.Linq.Table<tblHopdong> tblHopdongs
		{
			get
			{
				return this.GetTable<tblHopdong>();
			}
		}
		
		public System.Data.Linq.Table<tblHoso> tblHosos
		{
			get
			{
				return this.GetTable<tblHoso>();
			}
		}
		
		public System.Data.Linq.Table<tblLoaitaikhoan> tblLoaitaikhoans
		{
			get
			{
				return this.GetTable<tblLoaitaikhoan>();
			}
		}
		
		public System.Data.Linq.Table<tblLuong> tblLuongs
		{
			get
			{
				return this.GetTable<tblLuong>();
			}
		}
		
		public System.Data.Linq.Table<tblPhong> tblPhongs
		{
			get
			{
				return this.GetTable<tblPhong>();
			}
		}
		
		public System.Data.Linq.Table<tblTaikhoan> tblTaikhoans
		{
			get
			{
				return this.GetTable<tblTaikhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTrinhdo")]
	public partial class tblTrinhdo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Matd;
		
		private string _Tentd;
		
		private EntitySet<tblHoso> _tblHosos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatdChanging(string value);
    partial void OnMatdChanged();
    partial void OnTentdChanging(string value);
    partial void OnTentdChanged();
    #endregion
		
		public tblTrinhdo()
		{
			this._tblHosos = new EntitySet<tblHoso>(new Action<tblHoso>(this.attach_tblHosos), new Action<tblHoso>(this.detach_tblHosos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matd", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Matd
		{
			get
			{
				return this._Matd;
			}
			set
			{
				if ((this._Matd != value))
				{
					this.OnMatdChanging(value);
					this.SendPropertyChanging();
					this._Matd = value;
					this.SendPropertyChanged("Matd");
					this.OnMatdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentd", DbType="NVarChar(50)")]
		public string Tentd
		{
			get
			{
				return this._Tentd;
			}
			set
			{
				if ((this._Tentd != value))
				{
					this.OnTentdChanging(value);
					this.SendPropertyChanging();
					this._Tentd = value;
					this.SendPropertyChanged("Tentd");
					this.OnTentdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTrinhdo_tblHoso", Storage="_tblHosos", ThisKey="Matd", OtherKey="Matd")]
		public EntitySet<tblHoso> tblHosos
		{
			get
			{
				return this._tblHosos;
			}
			set
			{
				this._tblHosos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHosos(tblHoso entity)
		{
			this.SendPropertyChanging();
			entity.tblTrinhdo = this;
		}
		
		private void detach_tblHosos(tblHoso entity)
		{
			this.SendPropertyChanging();
			entity.tblTrinhdo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChucvu")]
	public partial class tblChucvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Macv;
		
		private string _Tencv;
		
		private EntitySet<tblHoso> _tblHosos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMacvChanging(string value);
    partial void OnMacvChanged();
    partial void OnTencvChanging(string value);
    partial void OnTencvChanged();
    #endregion
		
		public tblChucvu()
		{
			this._tblHosos = new EntitySet<tblHoso>(new Action<tblHoso>(this.attach_tblHosos), new Action<tblHoso>(this.detach_tblHosos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Macv", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Macv
		{
			get
			{
				return this._Macv;
			}
			set
			{
				if ((this._Macv != value))
				{
					this.OnMacvChanging(value);
					this.SendPropertyChanging();
					this._Macv = value;
					this.SendPropertyChanged("Macv");
					this.OnMacvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tencv", DbType="NVarChar(50)")]
		public string Tencv
		{
			get
			{
				return this._Tencv;
			}
			set
			{
				if ((this._Tencv != value))
				{
					this.OnTencvChanging(value);
					this.SendPropertyChanging();
					this._Tencv = value;
					this.SendPropertyChanged("Tencv");
					this.OnTencvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChucvu_tblHoso", Storage="_tblHosos", ThisKey="Macv", OtherKey="Macv")]
		public EntitySet<tblHoso> tblHosos
		{
			get
			{
				return this._tblHosos;
			}
			set
			{
				this._tblHosos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHosos(tblHoso entity)
		{
			this.SendPropertyChanging();
			entity.tblChucvu = this;
		}
		
		private void detach_tblHosos(tblHoso entity)
		{
			this.SendPropertyChanging();
			entity.tblChucvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHopdong")]
	public partial class tblHopdong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahd;
		
		private string _Tenhd;
		
		private string _Ghichu;
		
		private EntitySet<tblHoso> _tblHosos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahdChanging(string value);
    partial void OnMahdChanged();
    partial void OnTenhdChanging(string value);
    partial void OnTenhdChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    #endregion
		
		public tblHopdong()
		{
			this._tblHosos = new EntitySet<tblHoso>(new Action<tblHoso>(this.attach_tblHosos), new Action<tblHoso>(this.detach_tblHosos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahd", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahd
		{
			get
			{
				return this._Mahd;
			}
			set
			{
				if ((this._Mahd != value))
				{
					this.OnMahdChanging(value);
					this.SendPropertyChanging();
					this._Mahd = value;
					this.SendPropertyChanged("Mahd");
					this.OnMahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhd", DbType="NVarChar(50)")]
		public string Tenhd
		{
			get
			{
				return this._Tenhd;
			}
			set
			{
				if ((this._Tenhd != value))
				{
					this.OnTenhdChanging(value);
					this.SendPropertyChanging();
					this._Tenhd = value;
					this.SendPropertyChanged("Tenhd");
					this.OnTenhdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(50)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHopdong_tblHoso", Storage="_tblHosos", ThisKey="Mahd", OtherKey="Mahd")]
		public EntitySet<tblHoso> tblHosos
		{
			get
			{
				return this._tblHosos;
			}
			set
			{
				this._tblHosos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHosos(tblHoso entity)
		{
			this.SendPropertyChanging();
			entity.tblHopdong = this;
		}
		
		private void detach_tblHosos(tblHoso entity)
		{
			this.SendPropertyChanging();
			entity.tblHopdong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHoso")]
	public partial class tblHoso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Manv;
		
		private string _Hodem;
		
		private string _Ten;
		
		private string _Gioitinh;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Noisinh;
		
		private string _SoCMND;
		
		private string _Sodt;
		
		private System.Nullable<System.DateTime> _NgayvaoCT;
		
		private string _Dantoc;
		
		private string _BHXH;
		
		private string _Mahd;
		
		private string _Macv;
		
		private string _Matd;
		
		private string _Maphong;
		
		private EntitySet<tblLuong> _tblLuongs;
		
		private EntityRef<tblChucvu> _tblChucvu;
		
		private EntityRef<tblHopdong> _tblHopdong;
		
		private EntityRef<tblTrinhdo> _tblTrinhdo;
		
		private EntityRef<tblPhong> _tblPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManvChanging(string value);
    partial void OnManvChanged();
    partial void OnHodemChanging(string value);
    partial void OnHodemChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnNoisinhChanging(string value);
    partial void OnNoisinhChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnSodtChanging(string value);
    partial void OnSodtChanged();
    partial void OnNgayvaoCTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayvaoCTChanged();
    partial void OnDantocChanging(string value);
    partial void OnDantocChanged();
    partial void OnBHXHChanging(string value);
    partial void OnBHXHChanged();
    partial void OnMahdChanging(string value);
    partial void OnMahdChanged();
    partial void OnMacvChanging(string value);
    partial void OnMacvChanged();
    partial void OnMatdChanging(string value);
    partial void OnMatdChanged();
    partial void OnMaphongChanging(string value);
    partial void OnMaphongChanged();
    #endregion
		
		public tblHoso()
		{
			this._tblLuongs = new EntitySet<tblLuong>(new Action<tblLuong>(this.attach_tblLuongs), new Action<tblLuong>(this.detach_tblLuongs));
			this._tblChucvu = default(EntityRef<tblChucvu>);
			this._tblHopdong = default(EntityRef<tblHopdong>);
			this._tblTrinhdo = default(EntityRef<tblTrinhdo>);
			this._tblPhong = default(EntityRef<tblPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manv", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Manv
		{
			get
			{
				return this._Manv;
			}
			set
			{
				if ((this._Manv != value))
				{
					this.OnManvChanging(value);
					this.SendPropertyChanging();
					this._Manv = value;
					this.SendPropertyChanged("Manv");
					this.OnManvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hodem", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hodem
		{
			get
			{
				return this._Hodem;
			}
			set
			{
				if ((this._Hodem != value))
				{
					this.OnHodemChanging(value);
					this.SendPropertyChanging();
					this._Hodem = value;
					this.SendPropertyChanged("Hodem");
					this.OnHodemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(50)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noisinh", DbType="NVarChar(50)")]
		public string Noisinh
		{
			get
			{
				return this._Noisinh;
			}
			set
			{
				if ((this._Noisinh != value))
				{
					this.OnNoisinhChanging(value);
					this.SendPropertyChanging();
					this._Noisinh = value;
					this.SendPropertyChanged("Noisinh");
					this.OnNoisinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="NVarChar(50)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodt", DbType="NVarChar(50)")]
		public string Sodt
		{
			get
			{
				return this._Sodt;
			}
			set
			{
				if ((this._Sodt != value))
				{
					this.OnSodtChanging(value);
					this.SendPropertyChanging();
					this._Sodt = value;
					this.SendPropertyChanged("Sodt");
					this.OnSodtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayvaoCT", DbType="Date")]
		public System.Nullable<System.DateTime> NgayvaoCT
		{
			get
			{
				return this._NgayvaoCT;
			}
			set
			{
				if ((this._NgayvaoCT != value))
				{
					this.OnNgayvaoCTChanging(value);
					this.SendPropertyChanging();
					this._NgayvaoCT = value;
					this.SendPropertyChanged("NgayvaoCT");
					this.OnNgayvaoCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dantoc", DbType="NVarChar(50)")]
		public string Dantoc
		{
			get
			{
				return this._Dantoc;
			}
			set
			{
				if ((this._Dantoc != value))
				{
					this.OnDantocChanging(value);
					this.SendPropertyChanging();
					this._Dantoc = value;
					this.SendPropertyChanged("Dantoc");
					this.OnDantocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHXH", DbType="NVarChar(50)")]
		public string BHXH
		{
			get
			{
				return this._BHXH;
			}
			set
			{
				if ((this._BHXH != value))
				{
					this.OnBHXHChanging(value);
					this.SendPropertyChanging();
					this._BHXH = value;
					this.SendPropertyChanged("BHXH");
					this.OnBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mahd
		{
			get
			{
				return this._Mahd;
			}
			set
			{
				if ((this._Mahd != value))
				{
					if (this._tblHopdong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahdChanging(value);
					this.SendPropertyChanging();
					this._Mahd = value;
					this.SendPropertyChanged("Mahd");
					this.OnMahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Macv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Macv
		{
			get
			{
				return this._Macv;
			}
			set
			{
				if ((this._Macv != value))
				{
					if (this._tblChucvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMacvChanging(value);
					this.SendPropertyChanging();
					this._Macv = value;
					this.SendPropertyChanged("Macv");
					this.OnMacvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Matd
		{
			get
			{
				return this._Matd;
			}
			set
			{
				if ((this._Matd != value))
				{
					if (this._tblTrinhdo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatdChanging(value);
					this.SendPropertyChanging();
					this._Matd = value;
					this.SendPropertyChanged("Matd");
					this.OnMatdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Maphong
		{
			get
			{
				return this._Maphong;
			}
			set
			{
				if ((this._Maphong != value))
				{
					if (this._tblPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaphongChanging(value);
					this.SendPropertyChanging();
					this._Maphong = value;
					this.SendPropertyChanged("Maphong");
					this.OnMaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHoso_tblLuong", Storage="_tblLuongs", ThisKey="Manv", OtherKey="Manv")]
		public EntitySet<tblLuong> tblLuongs
		{
			get
			{
				return this._tblLuongs;
			}
			set
			{
				this._tblLuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChucvu_tblHoso", Storage="_tblChucvu", ThisKey="Macv", OtherKey="Macv", IsForeignKey=true)]
		public tblChucvu tblChucvu
		{
			get
			{
				return this._tblChucvu.Entity;
			}
			set
			{
				tblChucvu previousValue = this._tblChucvu.Entity;
				if (((previousValue != value) 
							|| (this._tblChucvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblChucvu.Entity = null;
						previousValue.tblHosos.Remove(this);
					}
					this._tblChucvu.Entity = value;
					if ((value != null))
					{
						value.tblHosos.Add(this);
						this._Macv = value.Macv;
					}
					else
					{
						this._Macv = default(string);
					}
					this.SendPropertyChanged("tblChucvu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHopdong_tblHoso", Storage="_tblHopdong", ThisKey="Mahd", OtherKey="Mahd", IsForeignKey=true)]
		public tblHopdong tblHopdong
		{
			get
			{
				return this._tblHopdong.Entity;
			}
			set
			{
				tblHopdong previousValue = this._tblHopdong.Entity;
				if (((previousValue != value) 
							|| (this._tblHopdong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHopdong.Entity = null;
						previousValue.tblHosos.Remove(this);
					}
					this._tblHopdong.Entity = value;
					if ((value != null))
					{
						value.tblHosos.Add(this);
						this._Mahd = value.Mahd;
					}
					else
					{
						this._Mahd = default(string);
					}
					this.SendPropertyChanged("tblHopdong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTrinhdo_tblHoso", Storage="_tblTrinhdo", ThisKey="Matd", OtherKey="Matd", IsForeignKey=true)]
		public tblTrinhdo tblTrinhdo
		{
			get
			{
				return this._tblTrinhdo.Entity;
			}
			set
			{
				tblTrinhdo previousValue = this._tblTrinhdo.Entity;
				if (((previousValue != value) 
							|| (this._tblTrinhdo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTrinhdo.Entity = null;
						previousValue.tblHosos.Remove(this);
					}
					this._tblTrinhdo.Entity = value;
					if ((value != null))
					{
						value.tblHosos.Add(this);
						this._Matd = value.Matd;
					}
					else
					{
						this._Matd = default(string);
					}
					this.SendPropertyChanged("tblTrinhdo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhong_tblHoso", Storage="_tblPhong", ThisKey="Maphong", OtherKey="Maphong", IsForeignKey=true)]
		public tblPhong tblPhong
		{
			get
			{
				return this._tblPhong.Entity;
			}
			set
			{
				tblPhong previousValue = this._tblPhong.Entity;
				if (((previousValue != value) 
							|| (this._tblPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPhong.Entity = null;
						previousValue.tblHosos.Remove(this);
					}
					this._tblPhong.Entity = value;
					if ((value != null))
					{
						value.tblHosos.Add(this);
						this._Maphong = value.Maphong;
					}
					else
					{
						this._Maphong = default(string);
					}
					this.SendPropertyChanged("tblPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLuongs(tblLuong entity)
		{
			this.SendPropertyChanging();
			entity.tblHoso = this;
		}
		
		private void detach_tblLuongs(tblLuong entity)
		{
			this.SendPropertyChanging();
			entity.tblHoso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLoaitaikhoan")]
	public partial class tblLoaitaikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Maloai;
		
		private string _TenLoai;
		
		private EntitySet<tblTaikhoan> _tblTaikhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaloaiChanging(string value);
    partial void OnMaloaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public tblLoaitaikhoan()
		{
			this._tblTaikhoans = new EntitySet<tblTaikhoan>(new Action<tblTaikhoan>(this.attach_tblTaikhoans), new Action<tblTaikhoan>(this.detach_tblTaikhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Maloai
		{
			get
			{
				return this._Maloai;
			}
			set
			{
				if ((this._Maloai != value))
				{
					this.OnMaloaiChanging(value);
					this.SendPropertyChanging();
					this._Maloai = value;
					this.SendPropertyChanged("Maloai");
					this.OnMaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaitaikhoan_tblTaikhoan", Storage="_tblTaikhoans", ThisKey="Maloai", OtherKey="Maloai")]
		public EntitySet<tblTaikhoan> tblTaikhoans
		{
			get
			{
				return this._tblTaikhoans;
			}
			set
			{
				this._tblTaikhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTaikhoans(tblTaikhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaitaikhoan = this;
		}
		
		private void detach_tblTaikhoans(tblTaikhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaitaikhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLuong")]
	public partial class tblLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _Ngay;
		
		private string _Manv;
		
		private string _Songaylv;
		
		private string _Tiencong1ngay;
		
		private string _Sogiotangca;
		
		private string _Luong1giotangca;
		
		private string _BHXH;
		
		private string _Thuong;
		
		private string _Tongluong;
		
		private EntityRef<tblHoso> _tblHoso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNgayChanging(System.DateTime value);
    partial void OnNgayChanged();
    partial void OnManvChanging(string value);
    partial void OnManvChanged();
    partial void OnSongaylvChanging(string value);
    partial void OnSongaylvChanged();
    partial void OnTiencong1ngayChanging(string value);
    partial void OnTiencong1ngayChanged();
    partial void OnSogiotangcaChanging(string value);
    partial void OnSogiotangcaChanged();
    partial void OnLuong1giotangcaChanging(string value);
    partial void OnLuong1giotangcaChanged();
    partial void OnBHXHChanging(string value);
    partial void OnBHXHChanged();
    partial void OnThuongChanging(string value);
    partial void OnThuongChanged();
    partial void OnTongluongChanging(string value);
    partial void OnTongluongChanged();
    #endregion
		
		public tblLuong()
		{
			this._tblHoso = default(EntityRef<tblHoso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manv", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Manv
		{
			get
			{
				return this._Manv;
			}
			set
			{
				if ((this._Manv != value))
				{
					if (this._tblHoso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManvChanging(value);
					this.SendPropertyChanging();
					this._Manv = value;
					this.SendPropertyChanged("Manv");
					this.OnManvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Songaylv", DbType="NVarChar(50)")]
		public string Songaylv
		{
			get
			{
				return this._Songaylv;
			}
			set
			{
				if ((this._Songaylv != value))
				{
					this.OnSongaylvChanging(value);
					this.SendPropertyChanging();
					this._Songaylv = value;
					this.SendPropertyChanged("Songaylv");
					this.OnSongaylvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiencong1ngay", DbType="NVarChar(50)")]
		public string Tiencong1ngay
		{
			get
			{
				return this._Tiencong1ngay;
			}
			set
			{
				if ((this._Tiencong1ngay != value))
				{
					this.OnTiencong1ngayChanging(value);
					this.SendPropertyChanging();
					this._Tiencong1ngay = value;
					this.SendPropertyChanged("Tiencong1ngay");
					this.OnTiencong1ngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sogiotangca", DbType="NVarChar(50)")]
		public string Sogiotangca
		{
			get
			{
				return this._Sogiotangca;
			}
			set
			{
				if ((this._Sogiotangca != value))
				{
					this.OnSogiotangcaChanging(value);
					this.SendPropertyChanging();
					this._Sogiotangca = value;
					this.SendPropertyChanged("Sogiotangca");
					this.OnSogiotangcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong1giotangca", DbType="NVarChar(50)")]
		public string Luong1giotangca
		{
			get
			{
				return this._Luong1giotangca;
			}
			set
			{
				if ((this._Luong1giotangca != value))
				{
					this.OnLuong1giotangcaChanging(value);
					this.SendPropertyChanging();
					this._Luong1giotangca = value;
					this.SendPropertyChanged("Luong1giotangca");
					this.OnLuong1giotangcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHXH", DbType="NVarChar(50)")]
		public string BHXH
		{
			get
			{
				return this._BHXH;
			}
			set
			{
				if ((this._BHXH != value))
				{
					this.OnBHXHChanging(value);
					this.SendPropertyChanging();
					this._BHXH = value;
					this.SendPropertyChanged("BHXH");
					this.OnBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thuong", DbType="NVarChar(50)")]
		public string Thuong
		{
			get
			{
				return this._Thuong;
			}
			set
			{
				if ((this._Thuong != value))
				{
					this.OnThuongChanging(value);
					this.SendPropertyChanging();
					this._Thuong = value;
					this.SendPropertyChanged("Thuong");
					this.OnThuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tongluong", DbType="NVarChar(50)")]
		public string Tongluong
		{
			get
			{
				return this._Tongluong;
			}
			set
			{
				if ((this._Tongluong != value))
				{
					this.OnTongluongChanging(value);
					this.SendPropertyChanging();
					this._Tongluong = value;
					this.SendPropertyChanged("Tongluong");
					this.OnTongluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHoso_tblLuong", Storage="_tblHoso", ThisKey="Manv", OtherKey="Manv", IsForeignKey=true)]
		public tblHoso tblHoso
		{
			get
			{
				return this._tblHoso.Entity;
			}
			set
			{
				tblHoso previousValue = this._tblHoso.Entity;
				if (((previousValue != value) 
							|| (this._tblHoso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHoso.Entity = null;
						previousValue.tblLuongs.Remove(this);
					}
					this._tblHoso.Entity = value;
					if ((value != null))
					{
						value.tblLuongs.Add(this);
						this._Manv = value.Manv;
					}
					else
					{
						this._Manv = default(string);
					}
					this.SendPropertyChanged("tblHoso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhong")]
	public partial class tblPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Maphong;
		
		private string _Tenphong;
		
		private EntitySet<tblHoso> _tblHosos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphongChanging(string value);
    partial void OnMaphongChanged();
    partial void OnTenphongChanging(string value);
    partial void OnTenphongChanged();
    #endregion
		
		public tblPhong()
		{
			this._tblHosos = new EntitySet<tblHoso>(new Action<tblHoso>(this.attach_tblHosos), new Action<tblHoso>(this.detach_tblHosos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Maphong
		{
			get
			{
				return this._Maphong;
			}
			set
			{
				if ((this._Maphong != value))
				{
					this.OnMaphongChanging(value);
					this.SendPropertyChanging();
					this._Maphong = value;
					this.SendPropertyChanged("Maphong");
					this.OnMaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenphong", DbType="NVarChar(50)")]
		public string Tenphong
		{
			get
			{
				return this._Tenphong;
			}
			set
			{
				if ((this._Tenphong != value))
				{
					this.OnTenphongChanging(value);
					this.SendPropertyChanging();
					this._Tenphong = value;
					this.SendPropertyChanged("Tenphong");
					this.OnTenphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhong_tblHoso", Storage="_tblHosos", ThisKey="Maphong", OtherKey="Maphong")]
		public EntitySet<tblHoso> tblHosos
		{
			get
			{
				return this._tblHosos;
			}
			set
			{
				this._tblHosos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHosos(tblHoso entity)
		{
			this.SendPropertyChanging();
			entity.tblPhong = this;
		}
		
		private void detach_tblHosos(tblHoso entity)
		{
			this.SendPropertyChanging();
			entity.tblPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTaikhoan")]
	public partial class tblTaikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Tendangnhap;
		
		private string _Matkhau;
		
		private string _Tenhienthi;
		
		private string _Maloai;
		
		private EntityRef<tblLoaitaikhoan> _tblLoaitaikhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTendangnhapChanging(string value);
    partial void OnTendangnhapChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnTenhienthiChanging(string value);
    partial void OnTenhienthiChanged();
    partial void OnMaloaiChanging(string value);
    partial void OnMaloaiChanged();
    #endregion
		
		public tblTaikhoan()
		{
			this._tblLoaitaikhoan = default(EntityRef<tblLoaitaikhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tendangnhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Tendangnhap
		{
			get
			{
				return this._Tendangnhap;
			}
			set
			{
				if ((this._Tendangnhap != value))
				{
					this.OnTendangnhapChanging(value);
					this.SendPropertyChanging();
					this._Tendangnhap = value;
					this.SendPropertyChanged("Tendangnhap");
					this.OnTendangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(50)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhienthi", DbType="NVarChar(50)")]
		public string Tenhienthi
		{
			get
			{
				return this._Tenhienthi;
			}
			set
			{
				if ((this._Tenhienthi != value))
				{
					this.OnTenhienthiChanging(value);
					this.SendPropertyChanging();
					this._Tenhienthi = value;
					this.SendPropertyChanged("Tenhienthi");
					this.OnTenhienthiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloai", DbType="NVarChar(50)")]
		public string Maloai
		{
			get
			{
				return this._Maloai;
			}
			set
			{
				if ((this._Maloai != value))
				{
					if (this._tblLoaitaikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaloaiChanging(value);
					this.SendPropertyChanging();
					this._Maloai = value;
					this.SendPropertyChanged("Maloai");
					this.OnMaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaitaikhoan_tblTaikhoan", Storage="_tblLoaitaikhoan", ThisKey="Maloai", OtherKey="Maloai", IsForeignKey=true)]
		public tblLoaitaikhoan tblLoaitaikhoan
		{
			get
			{
				return this._tblLoaitaikhoan.Entity;
			}
			set
			{
				tblLoaitaikhoan previousValue = this._tblLoaitaikhoan.Entity;
				if (((previousValue != value) 
							|| (this._tblLoaitaikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLoaitaikhoan.Entity = null;
						previousValue.tblTaikhoans.Remove(this);
					}
					this._tblLoaitaikhoan.Entity = value;
					if ((value != null))
					{
						value.tblTaikhoans.Add(this);
						this._Maloai = value.Maloai;
					}
					else
					{
						this._Maloai = default(string);
					}
					this.SendPropertyChanged("tblLoaitaikhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
